Changed install into inside folder

diff --git a/install b/install
--- a/install
+++ b/install
@@ -3,8 +3,12 @@
 
 
 # Installation program for projia.
-# This program removes itself when installation finished.
-mv Projia $HOME/.projia                                                   && \
-ln -s     $HOME/.projia/run $HOME/.bash_tools/projia                      && \
-rm $HOME/.projia/install                                                  && \
-echo "Projia installation done (you can find it in ~/.projia)."
+# This program removes itself when it finishes.
+mv *  $HOME/.projia                                             && \
+ln -s $HOME/.projia/run     $HOME/.bash_tools/projia            && \
+rm    $HOME/.projia/install                                     && \
+echo "Projia installation done (you can find it in ~/.projia)." || {
+	echo "projia: Unable to install projia."
+	echo "        Are you executing this installer in its own directory ?"
+	exit 1
+}
